[[redirects]]
  from = "https://neocomusmusic.com/*"
  to = "/neocomus_website.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.neocomusmusic.com/*"
  to = "/neocomus_website.html"
  status = 200
  force = true
